"""Render local matrix skill files with resolved CLI skill paths."""

import subprocess
from importlib import metadata
from pathlib import Path

from cli_hub.registry import get_cli

MATRIX_SKILL_DIR = Path.home() / ".cli-hub" / "matrix"


def _find_repo_root():
    """Find the repository root via git, falling back to parent traversal."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0:
            root = Path(result.stdout.strip())
            if root.is_dir():
                return root
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    # Fallback: walk up from this file looking for .git
    current = Path(__file__).resolve().parent
    for parent in [current] + list(current.parents):
        if (parent / ".git").exists():
            return parent

    return None


def get_rendered_matrix_skill_path(name):
    """Return the local rendered SKILL.md path for a matrix."""
    return MATRIX_SKILL_DIR / f"{name}.SKILL.md"


def resolve_local_skill_path(cli):
    """Resolve an installed harness CLI's local SKILL.md path if possible."""
    if cli.get("_source", "harness") != "harness":
        return None

    dist_name = cli.get("dist_name") or f"cli-anything-{cli['name']}"
    try:
        dist = metadata.distribution(dist_name)
    except metadata.PackageNotFoundError:
        return _fallback_repo_skill_path(cli)

    for file in dist.files or []:
        file_str = str(file).replace("\\", "/")
        if file_str.endswith("/skills/SKILL.md") or file_str.endswith("skills/SKILL.md"):
            return str(dist.locate_file(file).resolve())

    return _fallback_repo_skill_path(cli)


def _fallback_repo_skill_path(cli):
    """Use the repo-relative skill path when available in the current checkout."""
    skill_ref = cli.get("skill_md")
    if not skill_ref or "://" in skill_ref or skill_ref.startswith("npx "):
        return None

    repo_root = _find_repo_root()
    if repo_root is None:
        return None
    candidate = repo_root / skill_ref
    if candidate.exists():
        return str(candidate.resolve())
    return None


def render_matrix_skill_file(matrix_item, installed=None):
    """Write a local matrix SKILL.md with resolved member skill paths."""
    output_path = get_rendered_matrix_skill_path(matrix_item["name"])
    output_path.parent.mkdir(parents=True, exist_ok=True)

    base_content = _load_matrix_skill_template(matrix_item).rstrip()
    injected_section = _render_injected_section(matrix_item, installed or {})
    output_path.write_text(
        f"{base_content}\n\n<!-- MATRIX_SKILL_PATHS:START -->\n\n{injected_section}\n\n<!-- MATRIX_SKILL_PATHS:END -->\n",
        encoding="utf-8",
    )
    return output_path


def _load_matrix_skill_template(matrix_item):
    """Load the tracked matrix skill template when available."""
    skill_ref = matrix_item.get("skill_md")
    if skill_ref and "://" not in skill_ref and not skill_ref.startswith("npx "):
        repo_root = _find_repo_root()
        if repo_root is not None:
            candidate = repo_root / skill_ref
            if candidate.exists():
                return candidate.read_text(encoding="utf-8")

    title = matrix_item.get("display_name", matrix_item["name"])
    description = matrix_item.get("description", "")
    return (
        f"# {title}\n\n"
        f"{description}\n\n"
        f"Install with `cli-hub matrix install {matrix_item['name']}`."
    )


def _render_injected_section(matrix_item, installed):
    """Render the injected skill reference section."""
    lines = [
        "## Installed CLI Skills",
        "",
        "Generated by `cli-hub matrix install` from the current local environment.",
        "",
        "| CLI | Entry Point | Canonical Skill | Local Skill | Status |",
        "|---|---|---|---|---|",
    ]

    for cli_name in matrix_item.get("clis", []):
        cli = get_cli(cli_name) or {"name": cli_name, "entry_point": cli_name}
        canonical_skill = cli.get("skill_md") or "—"
        local_skill = resolve_local_skill_path(cli) or "—"
        status = "installed" if cli_name in installed else "not installed"
        lines.append(
            f"| `{cli_name}` | `{cli.get('entry_point', '—')}` | "
            f"{canonical_skill} | {local_skill} | {status} |"
        )

    stage_tooling = _render_stage_tooling(matrix_item, installed)
    if stage_tooling:
        lines.append("")
        lines.append(stage_tooling)

    discovery = _render_discovery_section(matrix_item)
    if discovery:
        lines.append("")
        lines.append(discovery)

    return "\n".join(lines)


def _render_stage_tooling(matrix_item, installed):
    """Render per-stage tooling overview with goals and alternatives."""
    stages = matrix_item.get("stages", [])
    has_goals = any(s.get("goal") for s in stages)
    if not has_goals:
        return ""

    lines = [
        "## Stage Tooling Overview",
        "",
        "What is available for each stage on this system.",
        "",
    ]

    for stage in stages:
        goal = stage.get("goal")
        if not goal:
            continue

        lines.append(f"### {stage['name']}")
        lines.append(f"**Goal:** {goal}")
        lines.append("")

        for cli_name in stage.get("clis", []):
            marker = "installed" if cli_name in installed else "not installed"
            lines.append(f"- CLI: `{cli_name}` ({marker})")

        alts = stage.get("alternatives", {})
        if alts.get("python"):
            lines.append(f"- Python: {', '.join(alts['python'])}")
        if alts.get("api"):
            lines.append(f"- APIs: {', '.join(alts['api'])}")
        if alts.get("native"):
            lines.append(f"- Native: {', '.join(alts['native'])}")

        hints = stage.get("skill_search_hints", [])
        if hints:
            cmds = ", ".join(f'`npx skills search "{h}"`' for h in hints[:2])
            lines.append(f"- Search for skills: {cmds}")

        lines.append("")

    return "\n".join(lines)


def _render_discovery_section(matrix_item):
    """Render aggregated skill discovery commands from all stages."""
    all_hints = []
    for stage in matrix_item.get("stages", []):
        for hint in stage.get("skill_search_hints", []):
            if hint not in all_hints:
                all_hints.append(hint)

    if not all_hints:
        return ""

    lines = [
        "## Skill Discovery Commands",
        "",
        "Search for relevant skills and tools across all stages:",
        "",
        "```bash",
    ]

    for hint in all_hints:
        lines.append(f'npx skills search "{hint}"')

    lines.extend([
        "```",
        "",
        "Also check CLI-Hub:",
        "",
        "```bash",
    ])

    seen = set()
    for hint in all_hints:
        keyword = hint.split()[0].lower()
        if keyword not in seen:
            seen.add(keyword)
            lines.append(f"cli-hub search {keyword}")

    lines.append("```")

    return "\n".join(lines)
